import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/reset.scss";
import "@/styles/font.scss";
import "@/styles/var.scss";
import "@/styles/globals.scss";
import Header from "@/features/header/Header";
import Footer from "@/features/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Адвокат.ру",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
